// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXGSXVeLuTE7TD7jrvxvmU6aA848Y3EPE',
    appId: '1:868645499081:web:d9dd0e447528f1f5b85d18',
    messagingSenderId: '868645499081',
    projectId: 'tayyari-assignment',
    authDomain: 'tayyari-assignment.firebaseapp.com',
    storageBucket: 'tayyari-assignment.appspot.com',
    measurementId: 'G-03ECR8LM1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7cWCZFtbPLBzlsl1WAKWSexjnLKMpE-g',
    appId: '1:868645499081:android:9fd44e47a17b407ab85d18',
    messagingSenderId: '868645499081',
    projectId: 'tayyari-assignment',
    storageBucket: 'tayyari-assignment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG5d-pktPurHsK_ScNqnrdhpqzYSwc8xo',
    appId: '1:868645499081:ios:3ca262e10b4bcf73b85d18',
    messagingSenderId: '868645499081',
    projectId: 'tayyari-assignment',
    storageBucket: 'tayyari-assignment.appspot.com',
    androidClientId: '868645499081-2o6pqla4rkjbogihrvq1bp7c6u16q8m6.apps.googleusercontent.com',
    iosClientId: '868645499081-073bs2b11r6crbvon3sa919u42ijtd64.apps.googleusercontent.com',
    iosBundleId: 'com.example.tayyariAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG5d-pktPurHsK_ScNqnrdhpqzYSwc8xo',
    appId: '1:868645499081:ios:3ca262e10b4bcf73b85d18',
    messagingSenderId: '868645499081',
    projectId: 'tayyari-assignment',
    storageBucket: 'tayyari-assignment.appspot.com',
    androidClientId: '868645499081-2o6pqla4rkjbogihrvq1bp7c6u16q8m6.apps.googleusercontent.com',
    iosClientId: '868645499081-073bs2b11r6crbvon3sa919u42ijtd64.apps.googleusercontent.com',
    iosBundleId: 'com.example.tayyariAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXGSXVeLuTE7TD7jrvxvmU6aA848Y3EPE',
    appId: '1:868645499081:web:8f8ed5c8376e1f0bb85d18',
    messagingSenderId: '868645499081',
    projectId: 'tayyari-assignment',
    authDomain: 'tayyari-assignment.firebaseapp.com',
    storageBucket: 'tayyari-assignment.appspot.com',
    measurementId: 'G-J6N7JH8HCM',
  );

}